#!/bin/bash

# Scirpts to generate system information
currentDate=$(date)

hostName=$(hostname)
os=$(source /etc/os-release && echo "$PRETTY_NAME")
upTime=$(uptime -p)

cpuName=$(sudo lshw -class processer | grep -m 1 "product:")
ramSpecs=$(free -h | awk '/^Meme:/ {print $2}')
diskSize=$(lshw -class disk | grep -m 1 "product:")
videoCard=$(lshw -class display | grep -m 1 "product:")

fqdn=$(sudo hostname -f)
hostIp=$(sudo ip route | grep -i "/default/")
gateWay=$(sudo ip route | grep -i "Gateway")
dnsServer=$(resolvectl status | grep -i "Current DNS")

currentUsers=$($hostName + " " + $USER)
diskSpace=$(sudo df -h | grep '/dev/sda2')
processCount=$(sudo ps -e --no-headers | wc -l)
loadAvg=$(sudo uptime | awk -F 'load average:' '{print $2}')
listeningNetworkPorts=$(sudo ss -tuln | grep 'LISTEN')
ufwStatus=$(sudo ufw status)




# Runs cat program and begins system report
cat <<EOF

# System Report user and current date info
System Report Generated by $USER, $currentDate


System Information
------------------
# Displays hostname, Operating System, and current uptime
Hostname: $hostName
OS: $os
Uptime: $upTime


Hardware Information
--------------------
# Displays cpu stats, ram stats, disk(s) storage in MB, graphics display card name #
cpu: $cpuName
Ram: $ramSpecs
Disk(s):  $diskSize
Video: $videoCard


Network Information
-------------------
# Displays fqdn name, hosts ip, gateway ip, and DNS Server stats #
FQDN: $fqdn
Host Address: $hostIp
Gateway IP: $gateWay
$dnsServer


System Status
----------------
# Displays current usernames, disk space in MB, current process count, load average, listening network ports, UFW status
Users Logged In: $currentUsers
Disk Space:  
Process Count:
Load Averages:
Listening Network Ports:
UFW $ufwStatus



EOF
